<?php

namespace NPS\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Shop
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends EntityRepository
{
    //we will have an EntityManager here
    protected $em;

    /**
     * This function will be executed before any controller action
     */
    public function preExecute()
    {
        $this->em = $this->getEntityManager();
    }
}
