<?php

namespace NPS\CoreBundle\Repository;

use NPS\CoreBundle\Entity\Device;
use NPS\CoreBundle\Repository\BaseRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends BaseRepository
{
    public function createDevice($appKey, $user) {
        $device = new Device();
        $device->setAppKey($appKey);
        $device->setUser($user);

        $em = $this->getEntityManager();
        $em->persist($device);
        $em->flush();
    }
}
