<?php

namespace NPS\CoreBundle\Repository;

use NPS\CoreBundle\Entity\Device;
use Doctrine\ORM\EntityRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends EntityRepository
{
    public function createDevice($appKey, $user) {
        $device = new Device();
        $device->setAppKey($appKey);
        $device->setUser($user);

        $em = $this->getEntityManager();
        $em->persist($device);
        $em->flush();
    }

    /**
     * Update Google Cloud Messaging ID
     *
     * @param string $appKey
     * @param string $gcmId
     */
    public function updateGcmId($appKey, $gcmId)
    {
        $query = $this->createQueryBuilder('d')
            ->update()
            ->set('d.gcmId', ':gcmId')
            ->where('d.appKey = :appKey')
            ->setParameter('appKey', $appKey)
            ->setParameter('gcmId', $gcmId)
            ->getQuery();
        $query->execute();
    }

    /**
     * Remove devices which were logout with same gcmId
     *
     * @param string $appKey
     * @param string $gcmId
     */
    public function removeLogOutDevices($appKey, $gcmId)
    {
        $query = $this->createQueryBuilder('d')
            ->delete()
            ->where('d.appKey != :appKey')
            ->andWhere('d.gcmId = :gcmId')
            ->setParameter('appKey', $appKey)
            ->setParameter('gcmId', $gcmId)
            ->getQuery();
        $query->execute();
    }
}
