<?php

namespace NPS\CoreBundle\Repository;

use NPS\CoreBundle\Repository\BaseRepository;

/**
 * FeedHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedHistoryRepository extends BaseRepository
{
    /**
     * Get last feed history
     *
     * @param $feedId
     *
     * @return mixed
     */
    public function getLastHistory($feedId)
    {
        parent::preExecute();
        $repository = $this->em->getRepository('NPSCoreBundle:FeedHistory');
        $query = $repository->createQueryBuilder('fh')
            ->where('fh.feed = :feedId')
            ->orderBy('fh.id', 'DESC')
            ->setMaxResults(1)
            ->setParameter('feedId', $feedId)
            ->getQuery();
        $collection = $query->getResult();
        foreach ($collection as $value) {
            return $value;
        }

        return null;
    }
}
