<?php

namespace NPS\CoreBundle\Repository;

use NPS\CoreBundle\Entity\Feed;
use NPS\CoreBundle\Repository\BaseRepository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends BaseRepository
{
    /**
     * Check if user is subscribed
     * @param $userId
     * @param $feedId
     *
     * @return bool
     */
    public function checkUserSubscribed($userId, $feedId)
    {
        $em = $this->getEntityManager();
        $repository = $em->getRepository('NPSCoreBundle:UserFeed');
        $query = $repository->createQueryBuilder('o')
            ->where('o.user = :userId')
            ->andWhere('o.feed = :feedId')
            ->setParameter('userId', $userId)
            ->setParameter('feedId', $feedId)
            ->getQuery();
        $feedCollection = $query->getResult();

        if (count($feedCollection)) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Check if already exists this feed in data base
     * @param string $url
     *
     * @return Feed
     */
    public function checkExistFeedUrl($url)
    {
        $em = $this->getEntityManager();
        $feedRepo = $em->getRepository('NPSCoreBundle:Feed');
        $urlHash = sha1($url);
        $feed = $feedRepo->findOneByUrlHash($urlHash);

        return $feed;
    }

    /**
     * Get user's feeds list
     * @param $userId
     *
     * @return mixed
     */
    public function getUserFeeds($userId)
    {
        parent::preExecute();
        $repository = $this->em->getRepository('NPSCoreBundle:Feed');
        $query = $repository->createQueryBuilder('f')
            ->join('f.userFeeds', 'uf')
            ->join('uf.user', 'u')
            ->where('u.id = :userId')
            ->orderBy('f.title', 'ASC')
            ->setParameter('userId', $userId)
            ->getQuery();
        $feedCollection = $query->getResult();

        return $feedCollection;
    }

    /**
     * Get user's feeds list for api
     * @param int $userId
     * @param int $lastUpdate
     *
     * @return array
     */
    public function getUserFeedsApi($userId, $lastUpdate = 0)
    {
        parent::preExecute();
        $repository = $this->em->getRepository('NPSCoreBundle:Feed');
        $query = $repository->createQueryBuilder('f')
            ->select('f.id AS api_id, f.title, f.website, f.favicon, f.dateChange AS lastUpdate')
            ->join('f.userFeeds', 'uf')
            ->join('uf.user', 'u')
            ->where('u.id = :userId')
            ->andWhere('f.dateChange > :lastUpdate')
            ->orderBy('f.dateUp', 'ASC')
            ->setParameter('userId', $userId)
            ->setParameter('lastUpdate', $lastUpdate)
            ->getQuery();
        $feedCollection = $query->getResult();

        return $feedCollection;
    }
}
