<?php

namespace NPS\CoreBundle\Repository;

use NPS\CoreBundle\Entity\Item;
use NPS\CoreBundle\Entity\User;
use NPS\CoreBundle\Entity\UserItem;
use NPS\CoreBundle\Repository\BaseRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends BaseRepository
{
    /**
     * Change item status
     * @param User $user
     * @param Item $item
     * @param $statusGet
     * @param $statusSet
     * @param null $change
     *
     * @return boolean set status
     */
    public function changeStatus(User $user, Item $item, $statusGet, $statusSet, $change = null)
    {
        $em = $this->getEntityManager();
        $userItem = $this->hasItem($user->getId(), $item->getId());

        if ($userItem instanceof UserItem) {
            $status = $this->getNewStatus($userItem, $change, $statusGet);
        } else {
            $userItem = new UserItem();
            $userItem->setUser($user);
            $userItem->setItem($item);
            if ($change == 1) {
                $status = true;
            } else {
                $status = false;
            }
        }
        $userItem->$statusSet($status);
        $em->persist($userItem);
        $em->flush();

        return $status;
    }

    /**
     * Get new status for existing userItem
     * @param UserItem $userItem
     * @param $change
     * @param $statusGet
     *
     * @return bool
     */
    private function getNewStatus(UserItem $userItem, $change, $statusGet){
        if ($change == 1) {
            $status = true;
        } elseif ($change == 2)  {
            $status = false;
        } else {
            if ($userItem->$statusGet()) { //change actual status
                $status = false;
            } else {
                $status = true;
            }
        }

        return $status;
    }

    /**
     * Check if are relation between user and item.
     * @param $userId
     * @param $itemId
     *
     * @return null|Item
     */
    public function hasItem($userId, $itemId)
    {
        parent::preExecute();
        $repository = $this->em->getRepository('NPSCoreBundle:UserItem');
        $query = $repository->createQueryBuilder('o')
            ->where('o.user = :userId')
            ->andWhere('o.item = :itemId')
            ->setParameter('userId', $userId)
            ->setParameter('itemId', $itemId)
            ->getQuery();
        $itemCollection = $query->getResult();
        $item = null;

        if (count($itemCollection) == 1) {
            foreach ($itemCollection as $value) {
                $item = $value;
            }
        }

        return $item;
    }

    /**
     * Check if user can see this item
     * @param $userId
     * @param $itemId
     *
     * @return bool
     */
    public function canSee($userId, $itemId)
    {
        $em = $this->getEntityManager();
        $repository = $em->getRepository('NPSCoreBundle:Feed');
        $query = $repository->createQueryBuilder('f')
            ->join('f.userFeeds', 'uf')
            ->join('f.items', 'e')
            ->join('uf.user', 'u')
            ->where('u.id = :userId')
            ->andWhere('e.id = :itemId')
            ->setParameter('userId', $userId)
            ->setParameter('itemId', $itemId)
            ->getQuery();
        $feedCollection = $query->getResult();
        if (count($feedCollection)) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param integer $userId
     * @param array   $items
     */
    public function syncViewedItems($userId, $items)
    {
        parent::preExecute();
        foreach ($items as $itemData) {
            $userItem = $this->hasItem($userId, $itemData->id);
            $userItem->setIsUnread($itemData->is_unread);
            $userItem->setIsStared($itemData->is_stared);
            $this->em->persist($userItem);
        }
        $this->em->flush();
    }

    /**
     * Get users unread items
     * @param $userId
     * @param $feedId
     * @return mixed
     */
    public function getUnreadItemsApi($userId, $feedId = null)
    {
        parent::preExecute();
        $repository = $this->em->getRepository('NPSCoreBundle:Item');
        if ($feedId) {
            $query = $repository->createQueryBuilder('i')
                ->select('i.id AS api_id, f.id AS feed_id, i.title, i.link, i.content, ui.isStared AS is_stared, ui.isUnread AS is_unread, i.dateAdd AS date_add')
                ->leftJoin('i.userItems', 'ui')
                ->leftJoin('i.feed', 'f')
                ->where('ui.isUnread = :isUnread')
                ->andWhere('ui.user = :userId')
                ->andWhere('f.id = :feedId')
                ->setParameter('isUnread', true)
                ->setParameter('userId', $userId)
                ->setParameter('feedId', $feedId)
                ->getQuery();
        } else {
            $query = $repository->createQueryBuilder('i')
                ->select('i.id AS api_id, f.id AS feed_id, i.title, i.link, i.content, ui.isStared AS is_stared, ui.isUnread AS is_unread, i.dateAdd AS date_add')
                ->leftJoin('i.userItems', 'ui')
                ->leftJoin('i.feed', 'f')
                ->where('ui.isUnread = :isUnread')
                ->andWhere('ui.user = :userId')
                ->setParameter('isUnread', true)
                ->setParameter('userId', $userId)
                ->getQuery();
        }
        $itemCollection = $query->getResult();

        return $itemCollection;
    }

    /**
     * Get last feed items
     * @param $feedId
     * @param int $limit
     *
     * @return mixed
     */
    public function getLast($feedId, $limit = 25)
    {
        parent::preExecute();
        $repository = $this->em->getRepository('NPSCoreBundle:Item');
        $query = $repository->createQueryBuilder('i')
            ->where('i.feed = :feedId')
            ->orderBy('i.feed', 'DESC')
            ->setMaxResults($limit)
            ->setParameter('feedId', $feedId)
            ->getQuery();
        $itemCollection = $query->getResult();

        return $itemCollection;
    }

    /**
     * Get count of unread items by user and feed
     * @param $userId
     * @param $feedId
     *
     * @return int
     */
    public function countUnreadByFeedUser($userId, $feedId)
    {
        $feedCollection = $this->getUnreadByFeedUser($userId, $feedId);

       return count($feedCollection);
    }

    /**
     * Get unread items by user and feed
     * @param $userId
     * @param $feedId
     *
     * @return array
     */
    public function getUnreadByFeedUser($userId, $feedId)
    {
        parent::preExecute();
        $repository = $this->em->getRepository('NPSCoreBundle:UserItem');

        $query = $repository->createQueryBuilder('ui')
            ->join('ui.item', 'i')
            ->join('ui.user', 'u')
            ->where('u.id = :userId')
            ->andWhere('i.feed = :feedId')
            ->andWhere('ui.isUnread = :isUnread')
            ->setParameter('userId', $userId)
            ->setParameter('feedId', $feedId)
            ->setParameter('isUnread', true)
            ->getQuery();
        $itemCollection = $query->getResult();

        return $itemCollection;
    }
}