<?php

namespace NPS\CoreBundle\Repository;

use NPS\CoreBundle\Repository\BaseRepository;

/**
 * UserItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaterItemRepository extends BaseRepository
{
}
