<?php

namespace NPS\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use NPS\CoreBundle\Helper\NotificationHelper;
use NPS\CoreBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Check user data for login
     * @param $username
     * @param $password
     *
     * @return int|User
     */
    public function checkLogin($username, $password){
        $user = $this->findOneByUsername($username);

        if ($user instanceof User) {
            $appKey = sha1("checkPwd_".$user->getPassword());

            if ($password == $appKey) {
                return $user;
            } else {
                return NotificationHelper::ERROR_LOGIN_DATA;
            }
        } else {
            return NotificationHelper::ERROR_LOGIN_DATA;
        }
    }

    /**
     * Check if username or email exists
     * @param $username
     * @param $email
     * @return bool|int
     */
    public function checkUserExists($username, $email)
    {
        $user = $this->findOneByUsername($username);
        if ($user instanceof User) {
            return NotificationHelper::ERROR_USERNAME_EXISTS;
        }

        $user = $this->findOneByEmail($email);
        if ($user instanceof User) {
            if ($user->isRegistered()) {
                return NotificationHelper::ERROR_EMAIL_EXISTS;
            }
        }

        return false;
    }

    /**
     * Create User
     * @param $username
     * @param $email
     * @param $password
     *
     * @return User
     */
    public function createUser($username, $email, $password)
    {
        $entityManager = $this->getEntityManager();
        $user = new User();
        $user->setUsername($username);
        $user->setEmail($email);
        $user->setPassword($password);
        $entityManager->persist($user);
        $entityManager->flush();

        return $user;
    }

    /**
     * Subscribe email to newsletter
     * @param $email
     */
    public function subscribeToNewsletter($email)
    {
        $entityManager = $this->getEntityManager();
        if (!$this->isInNewsletter($email)) {
            $user = $this->findOneByEmail($email);
            if (!$user instanceof User) {
                $user = new User();
                $user->setEmail($email);
            }
            $user->setSubscribed(true);
            $entityManager->persist($user);
            $entityManager->flush();
        }
    }

    /**
     * Check if user are un newsletter list
     *
     * @param $email
     *
     * @return bool
     */
    public function isInNewsletter($email)
    {
        $user = $this->findOneByEmail($email);
        if ($user instanceof User) {
            if ($user->isSubscribed()) {
                return true;
            }
        }

        return false;
    }
}
