<?php

namespace NPS\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserItemRepository extends EntityRepository
{
    /**
     * Check if are relation between user and item.
     *
     * @param $userId
     * @param $itemId
     *
     * @return null|Item
     */
    public function hasItem($userId, $itemId)
    {
        $query = $this->createQueryBuilder('o')
            ->where('o.user = :userId')
            ->andWhere('o.item = :itemId')
            ->setParameter('userId', $userId)
            ->setParameter('itemId', $itemId)
            ->getQuery();
        $itemCollection = $query->getResult();
        $item = null;

        if (count($itemCollection) > 0) {
            foreach ($itemCollection as $value) {
                $item = $value;
            }
        }

        return $item;
    }

    /**
     * Get count of unread items by user and feed
     * @param $userId
     * @param $feedId
     *
     * @return int
     */
    public function countUnreadByFeedUser($userId, $feedId)
    {
        $feedCollection = $this->getUnreadByFeedUser($userId, $feedId);

        return count($feedCollection);
    }

    /**
     * Get unread items by user and feed
     *
     * @param $userId
     * @param $feedId
     *
     * @return array
     */
    public function getUnreadByFeedUser($userId, $feedId)
    {
        $query = $this->createQueryBuilder('ui')
            ->leftJoin('ui.item', 'i')
            ->where('ui.user = :userId')
            ->andWhere('i.feed = :feedId')
            ->andWhere('ui.unread = :unread')
            ->orderBy('i.dateAdd', 'DESC')
            ->setParameter('userId', $userId)
            ->setParameter('feedId', $feedId)
            ->setParameter('unread', true)
            ->getQuery();
        $itemCollection = $query->getResult();

        return $itemCollection;
    }

    /**
     * Update user items status
     *
     * @param array $userItems
     */
    public function syncViewedItems($userItems)
    {
        $query = "START TRANSACTION; ";
        $userItemTable = $this->getEntityManager()->getClassMetadata('NPSCoreBundle:UserItem')->getTableName();

        foreach ($userItems as $itemData) {
            $query.= "UPDATE ".$userItemTable." SET stared=".$itemData['is_stared'].", unread=".$itemData['is_unread']." WHERE id=".$itemData['ui_id']."; ";
        }
        $query .= "COMMIT;";

        $this->getEntityManager()->getConnection()->executeQuery($query);
    }

    /**
     * Get user's feeds with count of user's items
     *
     * @param integer $userId
     *
     * @return array
     */
    public function getUserFeedsForMenu($userId)
    {
        $query = $this->createQueryBuilder('ui')
            ->select('uf.id, uf.title, COUNT(ui.id) total')
            ->innerJoin('ui.item', 'i')
            ->innerJoin('i.feed', 'f')
            ->innerJoin('f.userFeeds', 'uf')
            ->where('ui.user = :userId')
            ->andWhere('uf.user = :userId')
            ->andWhere('ui.unread = :unread')
            ->andWhere('uf.deleted = :deleted')
            ->groupBy('f.id')
            ->orderBy('uf.title', 'ASC')
            ->setParameter('userId', $userId)
            ->setParameter('unread', true)
            ->setParameter('deleted', false)
            ->getQuery();

        return $query->getArrayResult();
    }

    /**
     * Get read items to check that unread items from api were read
     *
     * @param int   $userId   user id
     * @param array $itemsIds ids of unread items
     *
     * @return array
     */
    public function getReadItems($userId, $itemsIds)
    {
        $query = $this->createQueryBuilder('ui');
        $query
            ->select('i.id AS api_id')
            ->innerJoin('ui.item', 'i')
            ->add('where', $query->expr()->in('i.id', $itemsIds))
            ->andWhere('ui.unread = :unread')
            ->andWhere('ui.user = :userId')
            ->setParameter('unread', false)
            ->setParameter('userId', $userId);
        $query = $query->getQuery();

        return $query->getArrayResult();
    }

    /**
     * Get unread feed items ids
     *
     * @param int $userId
     * @param int $begin
     * @param int $limit
     *
     * @return array
     */
    public function getUnreadFeedItems($userId, $begin = 0, $limit = 300)
    {
        $userItemTable = $this->getEntityManager()->getClassMetadata('NPSCoreBundle:UserItem')->getTableName();
        $sql = "SELECT ui.id AS ui_id, ui.stared AS is_stared, ui.unread AS is_unread, ui.item_id
            FROM ".$userItemTable." ui
            WHERE ui.shared=false AND ui.unread=true AND ui.user_id=".$userId." LIMIT ".$begin.",".$limit.";";
        $query = $this->getEntityManager()->getConnection()->executeQuery($sql);

        return $query->fetchAll();
    }

    /**
     * Count unread feed items
     *
     * @param int $userId
     *
     * @return int
     */
    public function totalUnreadFeedItems($userId)
    {
        $query = $this->createQueryBuilder('ui');
        $query
            ->add('select', $query->expr()->count('ui'))
            ->where('ui.shared = :shared')
            ->andWhere('ui.unread = :unread')
            ->andWhere('ui.user = :userId')
            ->setParameter('shared', false)
            ->setParameter('unread', true)
            ->setParameter('userId', $userId);

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * Get users stared/favorite items
     *
     * @param int $userId
     *
     * @return array
     */
    public function getStaredItems($userId)
    {
        $query = $this->createQueryBuilder('ui')
            ->where('ui.user = :userId')
            ->andWhere('ui.stared = :stared')
            ->setParameter('userId', $userId)
            ->setParameter('stared', true)
            ->orderBy('ui.dateAdd', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
