imports:
    - { resource: security.yml }
    - { resource: parameters_dev.yml }

    - { resource: vendors/doctrine.yml }
    - { resource: vendors/endroid_gcm.yml }
    - { resource: vendors/eko_google_translate.yml }
    - { resource: vendors/fkr_simple_pie.yml }
    - { resource: vendors/fos_elastica.yml }
    - { resource: vendors/fos_rest.yml }
    - { resource: vendors/hwi_oauth.yml }
    - { resource: vendors/nelmio_api_doc.yml }
    - { resource: vendors/rs_queue.yml }
    - { resource: vendors/snc_redis.yml }
    - { resource: vendors/swiftmailer.yml }
    - { resource: vendors/undf_angular_js.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %nseck%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        name: NewpselSession
    fragments:       ~

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['NPSFrontendBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        uglifyjs2:
            bin: /usr/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
