parameters:
    locale: en
    nseck: newpsel_key201306

    database_driver:   pdo_mysql
    database_host:     mysql
    database_port:     ~
    database_name:     nps
    database_user:     root
    database_password: root

    mailer_user:       newpsel
    mailer_password:   n#06p04e2013r#s

    redis_cache_server:    redis://localhost/4
    redis_sessions_server: redis://localhost/5

    google_developer_key: AIzaSyCR7kFwJEvGR9LMGNUtgQko9G7791Nh218
    google_client_id:     8108991373-3pelt7s1pevojlhikoapq09bhldlknhf.apps.googleusercontent.com
    google_client_secret: Biq3NalcK51VK85sTfPLVKRz

    facebook_client_id:     149114668611897
    facebook_client_secret: f3cc27080c1c74f4519d8295f23f7fef

    twitter_client_id:     sDLzI0H30q9loeYFFsVrpTpQi
    twitter_client_secret: 04IAG55X30lFEUswnQLXEVucCZnxLVqXbhoj00LeHYFOqtPerd

    getpocket_key: 30933-85863e319abff6cd585202c0
