imports:
    - { resource: parameters.yml }

parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     nps
    database_user:     root
    database_password: denysp

    mailer_transport:  gmail
    mailer_host:       ~
    mailer_user:       newpsel
    mailer_password:   n#06p04e2013r#s

    secret:            newpsel_key201306

    redis_cache_server:    redis://localhost/4
    redis_sessions_server: redis://localhost/5