parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     nps
    database_user:     root
    database_password: denysp

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            newpsel_key201306

    redis_cache_server:    redis://localhost/4
    redis_sessions_server: redis://localhost/5
