nps_frontend:
    resource: "@NPSFrontendBundle/Resources/config/routing.yml"
    prefix:   /

nps_api:
    resource: "@NPSApiBundle/Resources/config/routing.yml"
    prefix:   /api

#BCCCronManager routing
BCCCronManagerBundle:
    resource: "@BCCCronManagerBundle/Resources/config/routing.xml"
    prefix:   /cron-manager