chicplace_web:
    resource: "@NPSFrontendBundle/Controller"
    prefix:   /web
    type:     annotation

#admin Sonata
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /admin/resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /admin/profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /admin/register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /admin/profile

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

#web
welcome:
    path: /
    defaults: { _controller: "NPSFrontendBundle:Default:index"}

privacy_policy:
    path: /privacypolicy
    defaults: { _controller: "NPSFrontendBundle:Default:privacyPolicy"}

nps_api:
    resource: "@NPSApiBundle/Resources/config/routing.yml"
    host:     api.%base_host%
    type:     rest

#hwi/oauth-bundle
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

sign_in:
    path: /sign_in
    defaults: { _controller: "NPSFrontendBundle:User:login"}

sign_up:
    path: /sign_up
    defaults: { _controller: "NPSFrontendBundle:User:signup"}

facebook_login:
    path: /login/check-facebook
    schemes: [https]

google_login:
    path: /login/check-google
    schemes: [https]

logout:
    path:   /logout

page_not_found:
    path:  "/{notfounduri}"
    requirements:
        notfounduri: .*
    defaults: { _controller: "NPSFrontendBundle:PageNotFound:view"}



