chicplace_web:
    resource: "@NPSFrontendBundle/Controller"
    prefix:   /web
    type:     annotation

welcome:
    path: /
    defaults: { _controller: "NPSFrontendBundle:Default:index"}

privacy_policy:
    path: /privacypolicy
    defaults: { _controller: "NPSFrontendBundle:Default:privacyPolicy"}

nps_api:
    resource: "@NPSApiBundle/Resources/config/routing.yml"
    prefix:   /api

#hwi/oauth-bundle
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

sign_in:
    path: /sign_in
    defaults: { _controller: "NPSFrontendBundle:User:login"}

sign_up:
    path: /sign_up
    defaults: { _controller: "NPSFrontendBundle:User:signup"}

facebook_login:
    path: /login/check-facebook
    schemes: [https]

google_login:
    path: /login/check-google
    schemes: [https]

twitter_login:
    path: /login/check-twitter
    schemes:  [https]

logout:
    path:   /logout

page_not_found:
    path:  "/{notfounduri}"
    requirements:
        notfounduri: .*
    defaults: { _controller: "NPSFrontendBundle:PageNotFound:view"}
