jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        entity_api:
            class: NPS\CoreBundle\Entity\User
            algorithm: sha512
            iterations: 5000
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
    #    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        my_custom_hwi_provider:
            id: ib_user.oauth_user_provider

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: true
            logout: true
            logout:
                path:   /logout
                target: /
            oauth:
                resource_owners:
                    google: "/login/check-google"
                    facebook: "/login/check-facebook"
                    twitter: "/login/check-twitter"
                login_path: /sign_in
                failure_path: /sign_in
                oauth_user_provider:
                    service: ib_user.oauth_user_provider
            remember_me:
                key:      "%nseck%"
                lifetime: 31536000 # 365 days in seconds
                always_remember_me: true
                remember_me_parameter: _remember_me
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        welcome:
            path: /*
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        api_area:
            path: /api/.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        web_area:
            path: /web/.*
            roles: ROLE_USER