jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        entity_api:
            class: NPS\ModelBundle\Entity\User
            algorithm: sha512
            iterations: 5000
            encode_as_base64: false

    #role_hierarchy:
    #    ROLE_ADMIN:       ROLE_USER
    #    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: passs, roles: [ 'ROLE_USER' ] }

    firewalls:
        admin_secured_area:
              pattern: /api/.*
              anonymous: ~
              form_login:
                  login_path: /api/login
              logout:
                  path:   /api/logout
                  target: /api/
        #members_secured_area:
        #    pattern: /members/.*
        #    provider: entity_members
        #    anonymous: ~
        #    form_login:
        #        check_path: /members/login_check
        #        login_path: /members/login
        #    logout:
        #        path:   /members/logout
        #        target: /members/
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
