services:
  api.device.service:
    class: NPS\ApiBundle\Services\Entity\DeviceApiService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@api.secure.service"
      - "@user.notifications"
      - "@api.user.service"

  api.feed.service:
    class: NPS\ApiBundle\Services\Entity\FeedApiService
    arguments:
      doctrine:         "@nps.entity.feed"
      api.secure:       "@api.secure.service"
      download_feeds:   "@download_feeds"
      event_dispatcher: "@event_dispatcher"

  api.filter.service:
    class: NPS\ApiBundle\Services\Entity\FilterApiService
    arguments: ["@nps.entity.filter", "@nps.entity.feed"]

  api.item.service:
    class: NPS\ApiBundle\Services\Entity\ItemApiService
    arguments:
      doctrine:   "@doctrine.orm.entity_manager"
      api.secure: "@api.secure.service"

  api.label.service:
    class: NPS\ApiBundle\Services\Entity\LabelApiService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@api.secure.service"
      - "@nps.entity.later"
      - "@snc_redis.default"
      - "@event_dispatcher"

  api.later_item.service:
    class: NPS\ApiBundle\Services\Entity\LaterItemApiService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@api.secure.service"
      - "@nps.launcher.queue"
      - "@nps.entity.later_item"

  api.source.service:
    class: NPS\ApiBundle\Services\Entity\SourceApiService
    arguments: ["@doctrine.orm.entity_manager"]

  api.user.service:
    class: NPS\ApiBundle\Services\Entity\UserApiService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@security.encoder_factory"
      - "@event_dispatcher"
      - "%nseck%"
