services:
    api.device.service:
            class: NPS\ApiBundle\Services\Entity\DeviceApiService
            arguments:
                doctrine:        @doctrine
                api.secure:      @api.secure.service
                encoder_factory: @security.encoder_factory
                nseck:           %nseck%

    api.feed.service:
        class: NPS\ApiBundle\Services\Entity\FeedApiService
        arguments:
            doctrine:         @doctrine
            api.secure:       @api.secure.service
            download_feeds:   @download_feeds
            event_dispatcher: @event_dispatcher

    api.item.service:
        class: NPS\ApiBundle\Services\Entity\ItemApiService
        arguments:
            doctrine:   @doctrine
            api.secure: @api.secure.service

    api.label.service:
        class: NPS\ApiBundle\Services\Entity\LabelApiService
        arguments:
            doctrine:         @doctrine
            api.secure:       @api.secure.service
            label:            @nps.entity.later
            server_cache:     @snc_redis.default
            event_dispatcher: @event_dispatcher

    api.later_item.service:
        class: NPS\ApiBundle\Services\Entity\LaterItemApiService
        arguments:
            doctrine:   @doctrine
            api.secure: @api.secure.service
            queue:      @nps.launcher.queue
            label_item: @nps.entity.later_item