services:
    nps.api.listener.label:
      class: NPS\ApiBundle\EventListener\LabelListener
      tags:
          - { name: kernel.event_listener, event: nps.label.modified, method: onLabelModified }
      arguments:
          gcm.service: "@nps.api.gcm.service"
          api.label:   "@api.label.service"

    nps.api.listener.feed:
      class: NPS\ApiBundle\EventListener\FeedListener
      tags:
          - { name: kernel.event_listener, event: nps.feed.modified, method: onFeedModified }
      arguments:
          gcm.service: "@nps.api.gcm.service"
