services:
    nps.api.listener.label:
      class: NPS\ApiBundle\EventListener\LabelListener
      tags:
          - { name: kernel.event_listener, event: nps.label.modified, method: onLabelModified }
      arguments:
          gcm.service: @nps.api.gcm.service