#User
api_login:
    pattern:  /login/
    defaults: { _controller: NPSApiBundle:User:login }
    requirements:
      _method: POST

api_sign_up:
    pattern:  /sign_up/
    defaults: { _controller: NPSApiBundle:User:signUp }
    requirements:
      _method: POST

#Feed
api_sync_feeds:
    pattern:  /sync_feeds/
    defaults: { _controller: NPSApiBundle:Feed:syncFeeds }
    requirements:
      _method: POST

api_add_feed:
    pattern:  /add_feed/
    defaults: { _controller: NPSApiBundle:Feed:addFeed }
    requirements:
      _method: POST

#Item
api_sync_unread:
    pattern:  /sync_unread/
    defaults: { _controller: NPSApiBundle:Item:syncUnread }
    requirements:
      _method: POST

#Label
api_sync_labels:
    pattern:  /sync_labels/
    defaults: { _controller: NPSApiBundle:Label:syncLabels }
    requirements:
      _method: POST

api_sync_later:
    pattern:  /sync_later/
    defaults: { _controller: NPSApiBundle:Label:syncLater }
    requirements:
      _method: POST