api_feeds_sync:
    pattern:  /feeds_sync/
    defaults: { _controller: NPSApiBundle:Feed:sync }
    requirements:
      _method: GET

api_login:
    pattern:  /login/
    defaults: { _controller: NPSApiBundle:User:login }
    requirements:
      _method: POST