#Chrome extension
chrome_add:
    pattern:  /chrome/add/
    defaults: { _controller: NPSApiBundle:Chrome:addPage }
    requirements:
      _method: POST

chrome_labels:
    pattern:  /chrome/labels/
    defaults: { _controller: NPSApiBundle:Chrome:getLabels }
    requirements:
      _method: POST

chrome_login:
    pattern:  /chrome/login/
    defaults: { _controller: NPSApiBundle:Chrome:login }
    requirements:
      _method: POST

chrome_request:
    pattern:  /chrome/request/
    defaults: { _controller: NPSApiBundle:Chrome:requestKey }
    requirements:
      _method: POST

#GCM
gcm_add_id:
    pattern:  /gcm/add_id/
    defaults: { _controller: NPSApiBundle:Gcm:addRegistrationId }
    requirements:
      _method: POST

#Feed
api_sync_feeds:
    pattern:  /sync_feeds/
    defaults: { _controller: NPSApiBundle:Feed:syncFeeds }
    requirements:
      _method: POST

api_add_feed:
    pattern:  /add_feed/
    defaults: { _controller: NPSApiBundle:Feed:addFeed }
    requirements:
      _method: POST

#Item
api_sync_unread:
    pattern:  /sync_unread/
    defaults: { _controller: NPSApiBundle:Item:syncItems }
    requirements:
      _method: POST

api_sync_later_items:
    pattern:  /sync_later_items/
    defaults: { _controller: NPSApiBundle:Item:syncLaterItems }
    requirements:
      _method: POST

#Label
api_sync_labels:
    pattern:  /sync_labels/
    defaults: { _controller: NPSApiBundle:Label:syncLabels }
    requirements:
      _method: POST

api_sync_later:
    pattern:  /sync_later/
    defaults: { _controller: NPSApiBundle:Label:syncLater }
    requirements:
      _method: POST

api_sync_dictate_items:
    pattern:  /sync_dictate_items/
    defaults: { _controller: NPSApiBundle:Label:syncDictateItems }
    requirements:
      _method: POST

api_sync_shared:
    pattern:  /sync_shared/
    defaults: { _controller: NPSApiBundle:Label:syncShared }
    requirements:
      _method: POST

#User
api_login:
    pattern:  /login/
    defaults: { _controller: NPSApiBundle:User:login }
    requirements:
      _method: POST

api_sign_up:
    pattern:  /sign_up/
    defaults: { _controller: NPSApiBundle:User:signUp }
    requirements:
      _method: POST