parameters:
#    nps_api.example.class: NPS\ApiBundle\Example

services:
    api_secure_service:
        class: NPS\ApiBundle\Services\SecureService
        arguments:
            doctrine:     @doctrine
            server_cache: @server_cache