services:
    api.secure.service:
        class: NPS\ApiBundle\Services\SecureService
        arguments:
            doctrine:     @doctrine
            server_cache: @snc_redis.default

    nps.api.gcm.service:
        class: NPS\ApiBundle\Services\GcmService
        arguments:
            gcm:               @endroid.gcm
            device_repository: @=service("doctrine.orm.entity_manager").getRepository("NPSCoreBundle:Device")