parameters:
#    nps_api.example.class: NPS\ApiBundle\Example

services:
    api_secure_service:
        class: NPS\ApiBundle\Services\SecureService
        arguments:
            doctrine:     @doctrine
            server_cache: @server_cache

    chrome_data_service:
        class: NPS\ApiBundle\Services\ChromeDataService
        arguments:
            doctrine:           @doctrine
            api_secure_service: @api_secure_service
            user.notifications: @user.notifications

    api.feed.service:
        class: NPS\ApiBundle\Services\FeedDataService
        arguments:
            doctrine:           @doctrine
            api_secure_service: @api_secure_service
            download_feeds:     @download_feeds