services:
    api.secure.service:
        class: NPS\ApiBundle\Services\SecureService
        arguments:
            doctrine:     @doctrine
            server_cache: @server_cache

#Entities
    api.device.service:
            class: NPS\ApiBundle\Services\Entity\DeviceApiService
            arguments:
                doctrine:           @doctrine
                api.secure.service: @api.secure.service

    api.feed.service:
        class: NPS\ApiBundle\Services\Entity\FeedApiService
        arguments:
            doctrine:           @doctrine
            api.secure.service: @api.secure.service
            download_feeds:     @download_feeds

    api.item.service:
        class: NPS\ApiBundle\Services\Entity\ItemApiService
        arguments:
            doctrine:           @doctrine
            item:               @item
            api.secure.service: @api.secure.service

    api.label.service:
        class: NPS\ApiBundle\Services\Entity\LabelApiService
        arguments:
            crawler:            @crawler
            doctrine:           @doctrine
            api.secure.service: @api.secure.service