parameters:
#    nps_model.example.class: NPS\ModelBundle\Example

services:
#    nps_model.example:
#        class: %nps_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
