services:
    nps.form.type.filter:
        class: NPS\FrontendBundle\Form\Type\FilterEditType
        arguments:
            filters:       "%filters%"
            entity_feed:   "@nps.entity.feed"
            entity_later:  "@nps.entity.later"
        tags:
            - { name: form.filter, alias: filters }

    nps.form.type.import.pocket:
        class: NPS\FrontendBundle\Form\Type\ImportPocketType
        arguments:
            entity_later:  "@nps.entity.later"
        tags:
            - { name: form.import.pocket, alias: pocket }

    nps.form.type.import.instapaper:
        class: NPS\FrontendBundle\Form\Type\ImportInstapaperType
        arguments:
            entity_later:  "@nps.entity.later"
        tags:
            - { name: form.import.instapaper, alias: instapaper }

    nps.form.type.import.readability:
        class: NPS\FrontendBundle\Form\Type\ImportReadabilityType
        arguments:
            entity_later:  "@nps.entity.later"
        tags:
            - { name: form.import.readability, alias: readability }

    nps.form.type.preference:
        class: NPS\FrontendBundle\Form\Type\PreferenceEditType
        arguments:
            entity_later:  "@nps.entity.later"
        tags:
            - { name: form.preference, alias: preference }
