#Default
homepage:
    path:  /
    defaults: { _controller: NPSFrontendBundle:Default:index }

login:
    path:  /login
    defaults: { _controller: NPSFrontendBundle:Default:login }
    methods: [GET]

login_process:
    path:  /login
    defaults: { _controller: NPSFrontendBundle:Default:processLogin }
    methods: [POST]

login_check:
    path:  /login_check
    defaults: { _controller: NPSFrontendBundle:Default:loginCheck }
    methods: [GET]

logout:
    path:  /logout

signup_process:
    path:  /signup
    defaults: { _controller: NPSFrontendBundle:Default:signupProcess }
    methods: [POST]

signup:
    path:  /signup
    defaults: { _controller: NPSFrontendBundle:Default:signup }
    methods: [GET]


#Item
items:
    path:  /items/{id}
    defaults: { _controller: NPSFrontendBundle:Item:list, id: 0 }
    requirements:
      id: \d+

item:
    path:  /item/{id}
    defaults: { _controller: NPSFrontendBundle:Item:view }
    requirements:
      id: \d+

item_read:
    path:  /item_read/{feedId}/{itemId}
    defaults: { _controller: NPSFrontendBundle:Item:read }
    requirements:
      id: \d+

item_starred:
    path:  /item_starred/{feedId}/{itemId}
    defaults: { _controller: NPSFrontendBundle:Item:star }
    requirements:
      id: \d+

#Feed
feeds:
    path:  /feeds
    defaults: { _controller: NPSFrontendBundle:Feed:list }

feeds_sync:
    path:  /feeds_sync
    defaults: { _controller: NPSFrontendBundle:Feed:sync }

feed_edit_process:
    path:  /feed_edit/{id}
    defaults: { _controller: NPSFrontendBundle:Feed:editProcess, id: 0 }
    methods: [POST]
    requirements:
      id: \d+

feed_edit:
    path:  /feed_edit/{id}
    defaults: { _controller: NPSFrontendBundle:Feed:edit, id: 0 }
    methods: [GET]
    requirements:
      id: \d+

feed_enabled:
    path:  /feed_enabled/{id}
    defaults: { _controller: NPSFrontendBundle:Feed:enabledState }
    requirements:
      id: \d+
