#Default
homepage:
    pattern:  /
    defaults: { _controller: NPSFrontendBundle:Default:index }

login:
    pattern:  /login
    defaults: { _controller: NPSFrontendBundle:Default:login }
    requirements:
        _method: GET

login_process:
    pattern:  /login
    defaults: { _controller: NPSFrontendBundle:Default:processLogin }
    requirements:
        _method: POST

login_check:
    pattern:  /login_check
    defaults: { _controller: NPSFrontendBundle:Default:loginCheck }
    requirements:
        _method: GET

logout:
    pattern:  /logout

signup_process:
    pattern:  /signup
    defaults: { _controller: NPSFrontendBundle:Default:signupProcess }
    requirements:
        _method: POST

signup:
    pattern:  /signup
    defaults: { _controller: NPSFrontendBundle:Default:signup }
    requirements:
        _method: GET


#Item
items:
    pattern:  /items/{id}
    defaults: { _controller: NPSFrontendBundle:Item:list, id: 0 }
    requirements:
      id: \d+

item:
    pattern:  /item/{id}
    defaults: { _controller: NPSFrontendBundle:Item:view }
    requirements:
      id: \d+

item_read:
    pattern:  /item_read/{feedId}/{itemId}
    defaults: { _controller: NPSFrontendBundle:Item:read }
    requirements:
      id: \d+

item_starred:
    pattern:  /item_starred/{feedId}/{itemId}
    defaults: { _controller: NPSFrontendBundle:Item:star }
    requirements:
      id: \d+

#Feed
feeds:
    pattern:  /feeds
    defaults: { _controller: NPSFrontendBundle:Feed:list }

feeds_sync:
    pattern:  /feeds_sync
    defaults: { _controller: NPSFrontendBundle:Feed:sync }

feed_edit_process:
    pattern:  /feed_edit/{id}
    defaults: { _controller: NPSFrontendBundle:Feed:editProcess, id: 0 }
    requirements:
      id: \d+
      _method: POST

feed_edit:
    pattern:  /feed_edit/{id}
    defaults: { _controller: NPSFrontendBundle:Feed:edit, id: 0 }
    requirements:
      id: \d+
      _method: GET

feed_enabled:
    pattern:  /feed_enabled/{id}
    defaults: { _controller: NPSFrontendBundle:Feed:enabledState }
    requirements:
      id: \d+