#Default
homepage:
    pattern:  /
    defaults: { _controller: NPSFrontendBundle:Default:index }

login:
    pattern:  /login
    defaults: { _controller: NPSFrontendBundle:Default:login }

login_check_process:
    pattern:  /login_check
    defaults: { _controller: NPSFrontendBundle:Default:processLogin }
    requirements:
        _method: POST

login_check:
    pattern:  /login_check
    defaults: { _controller: NPSFrontendBundle:Default:loginCheck }
    requirements:
        _method: GET

signup_process:
    pattern:  /signup
    defaults: { _controller: NPSFrontendBundle:Default:signupProcess }
    requirements:
        _method: POST

signup:
    pattern:  /signup
    defaults: { _controller: NPSFrontendBundle:Default:signup }
    requirements:
        _method: GET


#Entry
entries:
    pattern:  /entries/{id}
    defaults: { _controller: NPSFrontendBundle:Entry:list, id: 0 }
    requirements:
      id: \d+

entry:
    pattern:  /entry/{id}
    defaults: { _controller: NPSFrontendBundle:Entry:view }
    requirements:
      id: \d+

entry_read:
    pattern:  /entry_read/{feedId}/{entryId}
    defaults: { _controller: NPSFrontendBundle:Entry:read }
    requirements:
      id: \d+

entry_starred:
    pattern:  /entry_starred/{feedId}/{entryId}
    defaults: { _controller: NPSFrontendBundle:Entry:star }
    requirements:
      id: \d+

#Feed
feeds:
    pattern:  /feeds
    defaults: { _controller: NPSFrontendBundle:Feed:list }

feeds_sync:
    pattern:  /feeds_sync
    defaults: { _controller: NPSFrontendBundle:Feed:sync }

feed_edit_process:
    pattern:  /feed_edit/{id}
    defaults: { _controller: NPSFrontendBundle:Feed:editProcess, id: 0 }
    requirements:
      id: \d+
      _method: POST

feed_edit:
    pattern:  /feed_edit/{id}
    defaults: { _controller: NPSFrontendBundle:Feed:edit, id: 0 }
    requirements:
      id: \d+
      _method: GET

feed_enabled:
    pattern:  /feed_enabled/{id}
    defaults: { _controller: NPSFrontendBundle:Feed:enabledState }
    requirements:
      id: \d+