parameters:
#    nps_frontend.example.class: NPS\FrontendBundle\Example

services:
    system_notification:
        class: NPS\FrontendBundle\Services\SystemNotificationService
        arguments:
            session: @session