services:
  nps.abstract.entity:
    class: NPS\CoreBundle\Services\Entity\AbstractEntityService
    arguments:
      doctrine:     "@doctrine.orm.entity_manager"
      user_wrapper: "@nps.wrapper.user"
      notification: "@nps.manager.notification"

  nps.entity.feed:
    class: NPS\CoreBundle\Services\Entity\FeedService
    arguments: ["@doctrine.orm.entity_manager"]

  feed_history:
    class: NPS\CoreBundle\Services\Entity\FeedHistoryService
    parent: nps.abstract.entity

  nps.entity.filter:
    class: NPS\CoreBundle\Services\Entity\FilterService
    arguments: ["@doctrine.orm.entity_manager"]

  item:
    class: NPS\CoreBundle\Services\Entity\ItemService
    arguments:
      doctrine:     "@doctrine.orm.entity_manager"
      server_cache: "@snc_redis.default"
      filter:       "@nps.manager.filter"
      later_item:   "@nps.entity.later_item"
      queue:        "@nps.launcher.queue"

  nps.entity.later:
    class: NPS\CoreBundle\Services\Entity\LaterService
    parent: nps.abstract.entity
    calls:
      - [setRedis, ["@snc_redis.default"]]

  nps.entity.later_item:
    class: NPS\CoreBundle\Services\Entity\LaterItemService
    arguments:
      doctrine:     "@doctrine.orm.entity_manager"
      server_cache: "@snc_redis.default"
      user_item:    "@nps.entity.user_item"
      crawler:      "@nps.manager.crawler"
      queue:        "@nps.launcher.queue"

  nps.entity.user:
    class: NPS\CoreBundle\Services\Entity\UserService
    parent: nps.abstract.entity
    calls:
      - [setRedis, ["@snc_redis.default"]]
      - [setNotificationManager, ["@user.notifications"]]

  nps.entity.user_item:
    class: NPS\CoreBundle\Services\Entity\UserItemService
    parent: nps.abstract.entity
