services:
    nps.listener.feed:
      class: NPS\CoreBundle\EventListener\FeedListener
      tags:
          - { name: kernel.event_listener, event: nps.feed.created, method: onFeedCreated }
      arguments:
          item_repository:   @=service("doctrine.orm.entity_manager").getRepository("NPSCoreBundle:Item")
          language_detector: @nps.detector.language
          entity_manager:    @doctrine.orm.entity_manager

    nps.listener.user:
      class: NPS\CoreBundle\EventListener\UserListener
      tags:
          - { name: kernel.event_listener, event: nps.user.signup, method: onUserSignup }
      arguments:
          user_service: @nps.entity.user