services:
    nps.listener.feed:
      class: NPS\CoreBundle\EventListener\FeedListener
      tags:
          - { name: kernel.event_listener, event: nps.feed.created, method: onFeedCreated }
      arguments:
          item_repository:   @=service("doctrine.orm.entity_manager").getRepository("NPSCoreBundle:Item")
          language_detector: @nps.detector.language
          entity_manager:    @doctrine.orm.entity_manager
          crawler:           @nps.manager.crawler

    nps.listener.user:
      class: NPS\CoreBundle\EventListener\UserListener
      tags:
          - { name: kernel.event_listener, event: nps.user.signup, method: onUserSignUp }
      arguments:
          user_service: @nps.entity.user

    nps.listener.security:
      class: NPS\CoreBundle\EventListener\SecuritySuccessListener
      tags:
          - { name: kernel.event_listener, event: security.authentication.success, method: handle }
      arguments:
          user_wrapper: @nps.wrapper.user

#**External services **
    gedmo.listener.timestampable:
          class: Gedmo\Timestampable\TimestampableListener
          tags:
              - { name: doctrine.event_subscriber, connection: default }
          calls:
              - [ setAnnotationReader, [ @annotation_reader ] ]