services:
    nps.listener.user:
      class: NPS\CoreBundle\EventListener\UserListener
      tags:
          - { name: kernel.event_listener, event: nps.user.signup, method: onUserSignup }
      arguments:
          user_service: @nps.entity.user