services:
    nps.form.type.filter:
        class: NPS\FrontendBundle\Form\Type\FilterEditType
        arguments:
            filters:       "%filters%"
            entity_feed:   @nps.entity.feed
            entity_later:  @nps.entity.later

        tags:
            - { name: form.filter, alias: filters }