parameters:
#    nps_frontend.example.class: NPS\FrontendBundle\Example

services:
    download_feeds:
        class: NPS\CoreBundle\Services\DownloadFeedsService
        arguments:
            doctrine:         "@doctrine.orm.entity_manager"
            simple_pie:       "@fkr_simple_pie.rss"
            redis:            "@snc_redis.default"
            feed:             "@nps.frontend.entity.feed"
            item:             "@item"
            feed_history:     "@feed_history"
            event_dispatcher: "@event_dispatcher"

    nps.detector.language:
        class: NPS\CoreBundle\Services\LanguageDetectService
        arguments:
            google_detector: "@eko.google_translate.detector"

    nps.launcher.queue:
        class: NPS\CoreBundle\Services\QueueLauncherService
        arguments:
            rs_queue.producer: "@rs_queue.producer"

    nps.manager.crawler:
        class: Dpcat237\CrawlerBundle\Library\Crawler

    nps.manager.filter:
        class: NPS\CoreBundle\Services\FilteringManager
        arguments:
            doctrine: "@doctrine"
            redis:    "@snc_redis.default"
            logger:   "@logger"

    nps.manager.notification:
        class: NPS\CoreBundle\Services\NotificationManager
        arguments:
            logger:     "@logger"
            session:    "@session"
            translator: "@translator"

    notifications.abstract:
        class: NPS\CoreBundle\Services\AbstractEmailNotificationService
        abstract: true
        arguments:
            - "@templating"
            - "@translator"
            - "%mailer_user%"
            - "%mailer_password%"

    user.notifications:
        class: NPS\CoreBundle\Services\UserNotificationsService
        parent: notifications.abstract

    nps.wrapper.user:
        class: NPS\CoreBundle\Services\UserWrapper
        arguments: ["@security.token_storage", "@security.authorization_checker", "@session"]
        calls:
            - [ setCurrentUser ]

#** Auth **
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
    ib_user.oauth_user_provider:
        class: NPS\CoreBundle\Provider\OAuthProvider
        arguments: ["@=service('doctrine.orm.entity_manager').getRepository('NPSCoreBundle:User')", "@event_dispatcher", "@security.encoder_factory", %nseck%]

