parameters:
#    nps_frontend.example.class: NPS\FrontendBundle\Example

services:
    download_feeds:
        class: NPS\CoreBundle\Services\DownloadFeedsService
        arguments:
            doctrine:     @doctrine
            simple_pie:   @fkr_simple_pie.rss
            redis:        @snc_redis.default
            feed:         @nps.entity.feed
            item:         @item
            feed_history: @feed_history

    nps.detector.language:
        class: NPS\CoreBundle\Services\LanguageDetectService
        arguments:
            google_detector: @eko.google_translate.detector

    nps.launcher.queue:
        class: NPS\CoreBundle\Services\QueueLauncherService
        arguments:
            rs_queue.producer: @rs_queue.producer

    nps.manager.crawler:
        class: NPS\CoreBundle\Services\CrawlerManager

    nps.manager.filter:
        class: NPS\CoreBundle\Services\FilteringManager
        arguments:
            doctrine: @doctrine
            redis:    @snc_redis.default
            logger:   @logger

    nps.manager.notification:
        class: NPS\CoreBundle\Services\NotificationManager
        arguments:
            logger:     @logger
            session:    @session
            translator: @translator

    user.notifications:
        class: NPS\CoreBundle\Services\UserNotificationsService
        arguments:
            templating: @templating
            mailer:     @mailer
            translator: @translator

    nps.wrapper.user:
        class: NPS\CoreBundle\Services\UserWrapper
        arguments:
            security: @security.context
        calls:
            - [ setCurrentUser ]

#** Auth **
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
    ib_user.oauth_user_provider:
        class: NPS\CoreBundle\Provider\OAuthProvider
        arguments: [@=service("doctrine.orm.entity_manager").getRepository("NPSCoreBundle:User"), @security.encoder_factory, %nseck%]

