services:
    gedmo.listener.timestampable:
          class: Gedmo\Timestampable\TimestampableListener
          tags:
              - { name: doctrine.event_subscriber, connection: default }
          calls:
              - [ setAnnotationReader, [ @annotation_reader ] ]

    crawler:
        class: NPS\CoreBundle\Services\CrawlerService
        arguments:
            doctrine:          @doctrine
            rs_queue.producer: @rs_queue.producer

    download_feeds:
        class: NPS\CoreBundle\Services\DownloadFeedsService
        arguments:
            doctrine:     @doctrine
            simple_pie:   @fkr_simple_pie.rss
            item:         @item

    server_cache:
        class: NPS\CoreBundle\Services\CacheService
        arguments: ['@snc_redis.default', 3600]

    try:
        class: NPS\CoreBundle\Services\TryService
        arguments:
            doctrine:     @doctrine
            server_cache: @server_cache
            crawler:      @crawler
            simple_pie:   @fkr_simple_pie.rss

    user.notifications:
        class: NPS\CoreBundle\Services\UserNotificationsService
        arguments:
            templating: @templating
            mailer:     @mailer
            translator: @translator

#Entities
    feed:
        class: NPS\CoreBundle\Services\Entity\FeedService
        arguments:
            doctrine:            @doctrine
            logger:              @logger
            system_notification: @system_notification

    item:
        class: NPS\CoreBundle\Services\Entity\ItemService
        arguments:
            doctrine:     @doctrine
            server_cache: @server_cache

    label:
        class: NPS\CoreBundle\Services\Entity\LabelService
        arguments:
            doctrine:            @doctrine
            logger:              @logger
            system_notification: @system_notification

    later_item:
        class: NPS\CoreBundle\Services\Entity\LaterItemService
        arguments:
            doctrine:     @doctrine
            server_cache: @server_cache
            item:         @item

    user:
        class: NPS\CoreBundle\Services\Entity\UserService
        arguments:
            doctrine:            @doctrine
            logger:              @logger
            system_notification: @system_notification