services:
    crawler:
        class: NPS\CoreBundle\Services\CrawlerService
        arguments:
            doctrine:          @doctrine
            rs_queue.producer: @rs_queue.producer

    download_feeds:
        class: NPS\CoreBundle\Services\DownloadFeedsService
        arguments:
            doctrine:     @doctrine
            simple_pie:   @fkr_simple_pie.rss
            redis:        @snc_redis.default
            feed:         @nps.entity.feed
            item:         @item
            feed_history: @feed_history

    try:
        class: NPS\CoreBundle\Services\TryService
        arguments:
            doctrine:     @doctrine
            server_cache: @snc_redis.default
            crawler:      @crawler
            simple_pie:   @fkr_simple_pie.rss

    nps.manager.filter:
        class: NPS\CoreBundle\Services\FilteringManager
        arguments:
            doctrine: @doctrine
            redis:    @snc_redis.default
            logger:   @logger

    user.notifications:
        class: NPS\CoreBundle\Services\UserNotificationsService
        arguments:
            templating: @templating
            mailer:     @mailer
            translator: @translator

    nps.wrapper.user:
        class: NPS\CoreBundle\Services\UserWrapper
        arguments:
            security: @security.context
        calls:
            - [ setCurrentUser ]

#**External services **
    gedmo.listener.timestampable:
          class: Gedmo\Timestampable\TimestampableListener
          tags:
              - { name: doctrine.event_subscriber, connection: default }
          calls:
              - [ setAnnotationReader, [ @annotation_reader ] ]