parameters:
#    nps_core.example.class: NPS\CoreBundle\Example

services:
    user.notifications:
        class: NPS\CoreBundle\Services\UserNotifications
        arguments:
            templating: @templating
            mailer:     @mailer
            translator: @translator