<?php

namespace NPS\ModelBundle\Repository;

use NPS\ModelBundle\Repository\BaseRepository;

/**
 * UserFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFeedRepository extends BaseRepository
{
}
