services:
  newpsel.admin.source:
    class: NPS\AdminBundle\Admin\SourceAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Source", label: "Sources" }
    arguments:
        - ~
        - NPS\CoreBundle\Entity\Source
        - ~

  newpsel.admin.source_category:
    class: NPS\AdminBundle\Admin\SourceCategoryAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Source", label: "Source Categories" }
    arguments:
        - ~
        - NPS\CoreBundle\Entity\SourceCategory
        - ~
